# Default values for parameters.
adapters: CTGTAGGCACC
asite_disp_length_file: null
buffer: 250
build_indices: true
codon_positions_file: null
count_reads: true
count_threshold: 64
dataset: "dataset"
dedup_stats: false
dedup_umis: false
dir_in: null
dir_index: "index"
dir_out: "output"
dir_tmp: "tmp"
extract_umis: false
feature: CDS
features_file: null
fq_files: null
group_umis: false
is_riboviz_gff: true
job_email: null
job_email_events: beas
job_memory: 8G
job_name: riboviz
job_num_cpus: 4
job_parallel_env: mpi
job_runtime: '48:00:00'
make_bedgraph: true
max_read_length: 50
min_read_length: 10
multiplex_fq_files: null
nextflow_dag_file: nextflow-dag.html
nextflow_report_file: nextflow-report.html
nextflow_timeline_file: nextflow-timeline.html
nextflow_trace_file: nextflow-trace.tsv
nextflow_work_dir: work
num_processes: 1
orf_fasta_file: null
orf_gff_file: null
orf_index_prefix: null
output_metagene_normalized_profile: true
output_pdfs: true
primary_id: Name
publish_index_tmp: false
rpf: true
rrna_fasta_file: null
rrna_index_prefix: null
run_static_html: true
sample_sheet: null
samsort_memory: null
secondary_id: null
stop_in_feature: false
t_rna_file: null
trim_5p_mismatches: true
umi_regexp: null
validate_only: false
